// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyatzuljgwtrybtkdlbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5YXR6dWxqZ3d0cnlidGtkbGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzYwNzUsImV4cCI6MjA1OTk1MjA3NX0.XSBQnCaZexaOYk1i7csF3H3j4p4x4OKEIBECUybpX_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);